require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GaPageviewsRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # GaPageviewsRecord. As you add validations to GaPageviewsRecord, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "model_type" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GaPageviewsRecordsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ga_pageviews_records as @ga_pageviews_records" do
      ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ga_pageviews_records).should eq([ga_pageviews_record])
    end
  end

  describe "GET show" do
    it "assigns the requested ga_pageviews_record as @ga_pageviews_record" do
      ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
      get :show, {:id => ga_pageviews_record.to_param}, valid_session
      assigns(:ga_pageviews_record).should eq(ga_pageviews_record)
    end
  end

  describe "GET new" do
    it "assigns a new ga_pageviews_record as @ga_pageviews_record" do
      get :new, {}, valid_session
      assigns(:ga_pageviews_record).should be_a_new(GaPageviewsRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested ga_pageviews_record as @ga_pageviews_record" do
      ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
      get :edit, {:id => ga_pageviews_record.to_param}, valid_session
      assigns(:ga_pageviews_record).should eq(ga_pageviews_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GaPageviewsRecord" do
        expect {
          post :create, {:ga_pageviews_record => valid_attributes}, valid_session
        }.to change(GaPageviewsRecord, :count).by(1)
      end

      it "assigns a newly created ga_pageviews_record as @ga_pageviews_record" do
        post :create, {:ga_pageviews_record => valid_attributes}, valid_session
        assigns(:ga_pageviews_record).should be_a(GaPageviewsRecord)
        assigns(:ga_pageviews_record).should be_persisted
      end

      it "redirects to the created ga_pageviews_record" do
        post :create, {:ga_pageviews_record => valid_attributes}, valid_session
        response.should redirect_to(GaPageviewsRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ga_pageviews_record as @ga_pageviews_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        GaPageviewsRecord.any_instance.stub(:save).and_return(false)
        post :create, {:ga_pageviews_record => { "model_type" => "invalid value" }}, valid_session
        assigns(:ga_pageviews_record).should be_a_new(GaPageviewsRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GaPageviewsRecord.any_instance.stub(:save).and_return(false)
        post :create, {:ga_pageviews_record => { "model_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ga_pageviews_record" do
        ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
        # Assuming there are no other ga_pageviews_records in the database, this
        # specifies that the GaPageviewsRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GaPageviewsRecord.any_instance.should_receive(:update_attributes).with({ "model_type" => "MyString" })
        put :update, {:id => ga_pageviews_record.to_param, :ga_pageviews_record => { "model_type" => "MyString" }}, valid_session
      end

      it "assigns the requested ga_pageviews_record as @ga_pageviews_record" do
        ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
        put :update, {:id => ga_pageviews_record.to_param, :ga_pageviews_record => valid_attributes}, valid_session
        assigns(:ga_pageviews_record).should eq(ga_pageviews_record)
      end

      it "redirects to the ga_pageviews_record" do
        ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
        put :update, {:id => ga_pageviews_record.to_param, :ga_pageviews_record => valid_attributes}, valid_session
        response.should redirect_to(ga_pageviews_record)
      end
    end

    describe "with invalid params" do
      it "assigns the ga_pageviews_record as @ga_pageviews_record" do
        ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GaPageviewsRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ga_pageviews_record.to_param, :ga_pageviews_record => { "model_type" => "invalid value" }}, valid_session
        assigns(:ga_pageviews_record).should eq(ga_pageviews_record)
      end

      it "re-renders the 'edit' template" do
        ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GaPageviewsRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ga_pageviews_record.to_param, :ga_pageviews_record => { "model_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ga_pageviews_record" do
      ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => ga_pageviews_record.to_param}, valid_session
      }.to change(GaPageviewsRecord, :count).by(-1)
    end

    it "redirects to the ga_pageviews_records list" do
      ga_pageviews_record = GaPageviewsRecord.create! valid_attributes
      delete :destroy, {:id => ga_pageviews_record.to_param}, valid_session
      response.should redirect_to(ga_pageviews_records_url)
    end
  end

end
